USE CHINOOK;

-- ES.1 -- Recuperate tutte le tracce che abbiano come genere “Pop” o “Rock”.

SELECT T.NAME AS NOME_TRACCIA FROM TRACK T
JOIN GENRE G ON T.GENREID = G.GENREID
WHERE G.NAME = 'Pop' OR G.NAME = 'Rock'
ORDER BY NOME_TRACCIA;

-- ES.2 -- Elencate tutti gli artisti e/o gli album che inizino con la lettera “A”. 

SELECT ARTIST.NAME, ALBUM.TITLE FROM ARTIST
JOIN ALBUM ON ARTIST.ARTISTID = ALBUM.ALBUMID
WHERE ARTIST.NAME LIKE 'A%' AND ALBUM.TITLE LIKE 'A%';

-- ES.3 -- Recuperate i nomi degli album o degli artisti che abbiano pubblicazioni precedenti all’anno 2000.

SELECT DISTINCT ARTIST.NAME AS NOME_ARTISTA, ALBUM.TITLE AS TITOLO_ALBUM FROM ARTIST
JOIN ALBUM ON ARTIST.ARTISTID = ALBUM.ALBUMID
JOIN TRACK ON TRACK.ALBUMID = ALBUM.ALBUMID
JOIN INVOICELINE ON INVOICELINE.TRACKID = TRACK.TRACKID
JOIN INVOICE ON INVOICE.INVOICEID = INVOICELINE.INVOICEID
WHERE EXTRACT(YEAR FROM INVOICE.INVOICEDATE) < 2000;

-- ES. 4 Elencate tutte le tracce che hanno come genere “Jazz” o che durano meno di 3 minuti.

SELECT T.NAME AS NOME_TRACCIA FROM TRACK T
JOIN GENRE G ON T.GENREID = G.GENREID
WHERE G.NAME = 'Jazz' AND T.MILLISECONDS < 180000
ORDER BY NOME_TRACCIA;

-- ES. 5 -- Recuperate tutte le tracce più lunghe della durata media.

SELECT TRACK.NAME AS NOME_TRACCIA FROM TRACK
WHERE TRACK.MILLISECONDS > (SELECT AVG(TRACK.MILLISECONDS) FROM TRACK);

-- ES. 6 -- Individuate i generi che hanno tracce con una durata media maggiore di 4 minuti.

SELECT G.NAME AS NOME_GENERE FROM GENRE G
JOIN TRACK T ON T.GENREID = G.GENREID
WHERE T.MILLISECONDS > 240000
ORDER BY NOME_GENERE;

-- ES.7 -- Individuate gli artisti che hanno rilasciato più di un album.

SELECT ARTIST.NAME, COUNT(ALBUMID) AS NUMERO_ALBUM
FROM ARTIST
JOIN ALBUM ON ARTIST.ARTISTID = ALBUM.ARTISTID
GROUP BY ARTIST.ARTISTID
HAVING COUNT(ALBUM.ALBUMID)>1
ORDER BY COUNT(ALBUM.ALBUMID) DESC;

-- ES.8 -- Trovate la traccia più lunga in ogni album.

SELECT A.TITLE AS TITOLO_ALBUM, T.NAME AS NOME_TRACCIA, T.MILLISECONDS
FROM (
    SELECT T.ALBUMID, MAX(T.MILLISECONDS) AS DURATA_MAX
    FROM TRACK T
    GROUP BY T.ALBUMID
) AS MAX_DURATA_PER_ALBUM
JOIN TRACK T ON MAX_DURATA_PER_ALBUM.ALBUMID = T.ALBUMID AND MAX_DURATA_PER_ALBUM.DURATA_MAX = T.MILLISECONDS
JOIN ALBUM A ON A.ALBUMID = T.ALBUMID;

-- ES.9 -- Individuate la durata media delle tracce per ogni album.

SELECT A.TITLE AS TITOLO_ALBUM, AVG(T.MILLISECONDS) AS DURATA_MEDIA_TRACCE
FROM TRACK T
JOIN ALBUM A ON T.ALBUMID = A.ALBUMID
GROUP BY A.TITLE;

-- ES.10 -- Individuate gli album che hanno più di 20 tracce e mostrate il nome dell’album e il numero di tracce in esso contenute.

SELECT A.TITLE AS TITOLO_ALBUM, COUNT(T.TRACKID) AS NUMERO_TRACCE 
FROM ALBUM A
JOIN TRACK T ON A.ALBUMID = T.ALBUMID
GROUP BY A.ALBUMID, A.TITLE
HAVING COUNT(T.TRACKID) > 20;