USE CHINOOK;

-- Esercizio 1 -- Elencate il numero di tracce per ogni genere in ordine discendente, escludendo quei generi che hanno meno di 10 tracce.

SELECT COUNT(T.TRACKID) AS NUMERO_TRACCE, G.NAME AS NOME_GENERE FROM GENRE G
JOIN TRACK T ON G.GENREID = T.GENREID
GROUP BY G.GENREID, G.NAME
HAVING COUNT(T.TRACKID) > 10
ORDER BY NUMERO_TRACCE DESC;

-- Esercizio 2 -- Trovate le tre canzoni più costose.

SELECT T.NAME, (T.UNITPRICE) AS 'TOP 3 CANZONI COSTOSE'
FROM TRACK T
ORDER BY T.UNITPRICE DESC
LIMIT 3;

-- Esercizio 3 -- Elencate gli artisti che hanno canzoni più lunghe di 6 minuti.

SELECT A.NAME, T.MILLISECONDS/60000 AS MINUTI
FROM ARTIST A 
JOIN ALBUM AL ON AL.ARTISTID = A.ARTISTID
JOIN TRACK T ON AL.ALBUMID = T.ALBUMID
WHERE T.MILLISECONDS/60000 > 6
ORDER BY MINUTI DESC;

-- Esercizio 4 -- Individuate la durata media delle tracce per ogni genere.

SELECT G.NAME, ROUND(AVG(T.MILLISECONDS/60000), 2) AS MINUTI 
FROM TRACK T
JOIN GENRE G ON G.GENREID = T.GENREID
GROUP BY G.NAME;

-- Esercizio 5 -- Elencate tutte le canzoni con la parola “Love” nel titolo, ordinandole alfabeticamente prima per genere e poi per nome.

SELECT T.NAME, G.NAME FROM TRACK T 
JOIN GENRE G ON G.GENREID = T.GENREID
WHERE T.NAME LIKE '%LOVE%' 
ORDER BY G.NAME, T.NAME;

-- Esercizio 6 -- Trovate il costo medio per ogni tipologia di media.

SELECT M.NAME, ROUND(AVG(T.UNITPRICE), 2) AS 'PREZZO MEDIO'
FROM MEDIATYPE M
JOIN TRACK T ON M.MEDIATYPEID = T.MEDIATYPEID
GROUP BY M.NAME;

-- Esercizio 7 -- Individuate il genere con più tracce.

SELECT G.NAME AS GENERE, COUNT(*) AS TRACCE
FROM TRACK T
JOIN GENRE G ON T.GENREID = G.GENREID
GROUP BY G.NAME
ORDER BY TRACCE DESC
LIMIT 1;

-- Esercizio 8 -- Trovate gli artisti che hanno lo stesso numero di album dei Rolling Stones.

SELECT A.NAME AS ARTISTI, COUNT(*) AS ALBUM_TOT
FROM ALBUM AL
JOIN ARTIST A ON AL.ARTISTID = A.ARTISTID
WHERE AL.ARTISTID = (SELECT A.ARTISTID FROM ARTIST WHERE NAME = 'THE ROLLING STONES')
GROUP BY AL.ARTISTID, A.NAME
HAVING COUNT(*) = (SELECT COUNT(*) FROM ALBUM WHERE ARTISTID = (SELECT ARTISTID FROM ARTIST WHERE NAME = 'THE ROLLING STONES'));

-- Esercizio 9 -- Trovate l’artista con l’album più costoso.

SELECT A.NAME AS ARTISTA, AL.TITLE AS TITOLO_ALBUM, SUM(IL.UNITPRICE * IL.QUANTITY) AS VENDITE_TOTALI
FROM ARTIST A
JOIN ALBUM AL ON A.ARTISTID = AL.ARTISTID
JOIN TRACK T ON AL.ALBUMID = T.ALBUMID
JOIN INVOICELINE IL ON T.TRACKID = IL.TRACKID
GROUP BY A.NAME, AL.TITLE
ORDER BY VENDITE_TOTALI DESC
LIMIT 1;


